### ISSUE TITLE
Module does not detect Monster Core Token Pack.

### ISSUE THREAD

**Issue by jfn4th** [manuel-hegner/pf2e-all-tokens#4]
As the title says, the new Monster Core Token Pack is not detected by this module.

**Comment by roi007leaf** [comment]
It looks like there's a new mapping structure to the tokens

**Comment by manuel-hegner** [comment]
This should work now in version 1.6.

The images are not shown in the compendium browser, but I think that is missing support of the pf2e system for the new native way of adding art.
